import type { Metadata } from "next";
import "./globals.css";
import { Chelsea_Market, Farro } from "next/font/google";

const chelsea_Market = Chelsea_Market({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-chelsea-market",
});

const farro = Farro({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-farro",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${chelsea_Market.variable} ${farro.variable}`}>
        {children}
      </body>
    </html>
  );
}
